version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234567
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: community-center-api
    ports:
      - "8080:8080"
    depends_on:
      - mongo

volumes:
  mongo-data:
