server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://root:1234567@mongo:27017/community-db?authSource=admin

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    root: INFO
    com.paystore: DEBUG
